name: "hello-world"
arch: "${NFPM_PKG_ARCH}"
platform: "linux"
version: "${NFPM_PKG_VERSION}"
priority: "extra"
#prerelease: beta1
release: "${RELEASE_NUM}"
section: vcs
maintainer: "Josh Beard <josh@jbeard.dev>"
description: |
  FooBar is the great foo and bar software.
    And this can be in multiple lines!
vendor: "Josh Beard"
homepage: "http://github.com/joshbeard/testing-packaging"
license: "MIT"
contents:
- src: "${NFPM_PKG_SRC}"
  dst: /usr/bin/hello-world
  expand: true
