name: "${PACKAGE}"
arch: "${PKG_ARCH}"
platform: "linux"
version: "${VERSION}"
priority: "extra"
#prerelease: beta1
release: "${RELEASE}"
section: vcs
maintainer: "Josh Beard <josh@jbeard.dev>"
description: |
  FooBar is the great foo and bar software.
    And this can be in multiple lines!
vendor: "Josh Beard"
homepage: "http://github.com/joshbeard/testing-packaging"
license: "MIT"
contents:
- src: "${PKG_SRC}"
  dst: /usr/bin/hello-world
  expand: true
rpm:
  signature: key.gpg
deb:
  signature: key.gpg
