# Config for https://github.com/joshbeard/web-indexer
source: /mnt/repos
target: /mnt/repos
#target: s3://jbeard-test-pkgs
link_to_index: true
relative_links: true
title: get.jbeard.dev - {relativePath}
url: https://get.jbeard.dev
recursive: true
minify: true
