# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HelloWorld < Formula
  desc "Say Hello World - a test package"
  homepage "https://github.com/joshbeard/testing-packaging"
  version "0.11.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://get.jbeard.dev/pkg/0.11.1/hello-world_0.11.1_darwin_amd64.tar.gz"
      sha256 "cd1f8f92c5b1984c34cc8c0af7b1f39057e3da955bf07bb1ae9a6cb2f2bb38d7"

      def install
        bin.install "hello-world"
      end
    end
    if Hardware::CPU.arm?
      url "https://get.jbeard.dev/pkg/0.11.1/hello-world_0.11.1_darwin_arm64.tar.gz"
      sha256 "66d546ef66619c8146af55bc97c0999dc5a57e4106374bae0f02e2d1b349cc03"

      def install
        bin.install "hello-world"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://get.jbeard.dev/pkg/0.11.1/hello-world_0.11.1_linux_amd64.tar.gz"
      sha256 "b072d1495282a5d2f69a2a1ebaa47f426678ed4f1bfca76b241c413170b6e271"

      def install
        bin.install "hello-world"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://get.jbeard.dev/pkg/0.11.1/hello-world_0.11.1_linux_arm.tar.gz"
      sha256 "436a9a4ea1af8055e0d33d42133149d2e324d8c09d720d41829b48f4c9f096cf"

      def install
        bin.install "hello-world"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://get.jbeard.dev/pkg/0.11.1/hello-world_0.11.1_linux_arm64.tar.gz"
      sha256 "ccc0ad0abb1385377b4494855a24c310a20e9f7282a6cbe377660a0c4a425a3d"

      def install
        bin.install "hello-world"
      end
    end
  end

  test do
    system "#{bin}/hello-world --version"
  end
end
