# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HelloWorld < Formula
  desc "Say Hello World - a test package"
  homepage "https://github.com/joshbeard/testing-packaging"
  version "0.11.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://get.jbeard.dev/pkg/0.11.2/hello-world_0.11.2_darwin_amd64.tar.gz"
      sha256 "281d3db5927e7fd57707c6d1e67d21c4dbe4a29a1df6b3ae82c6991ef601099b"

      def install
        bin.install "hello-world"
      end
    end
    if Hardware::CPU.arm?
      url "https://get.jbeard.dev/pkg/0.11.2/hello-world_0.11.2_darwin_arm64.tar.gz"
      sha256 "f3e7d0c006d5342299e4d1bb94974e2cde6659d07a1df4b7d593a1e9927621ee"

      def install
        bin.install "hello-world"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://get.jbeard.dev/pkg/0.11.2/hello-world_0.11.2_linux_amd64.tar.gz"
      sha256 "eb8ef4200603e9bd5414abec3c7ce434f1376a95e766b212172bf503b3ff0df0"

      def install
        bin.install "hello-world"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://get.jbeard.dev/pkg/0.11.2/hello-world_0.11.2_linux_arm.tar.gz"
      sha256 "0f38f62524aa06a9745ab23d8d5552ec276b9b53f95a4251841c1d7501875bb3"

      def install
        bin.install "hello-world"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://get.jbeard.dev/pkg/0.11.2/hello-world_0.11.2_linux_arm64.tar.gz"
      sha256 "b3f622b0beefd9767efc180b9430e62eda0fb416ea89821e473862c5719a856b"

      def install
        bin.install "hello-world"
      end
    end
  end

  test do
    system "#{bin}/hello-world --version"
  end
end
