# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HelloWorld < Formula
  desc "Say Hello World - a test package"
  homepage "https://github.com/joshbeard/testing-packaging"
  version "0.11.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/joshbeard/testing-packaging/releases/download/0.11.0/hello-world_0.11.0_darwin_arm64.tar.gz"
      sha256 "9894ac634e2ed3681229d4cc4195b4f2ee9fd44ec93bc5813c44ddb1247f1ec3"

      def install
        bin.install "hello-world"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/joshbeard/testing-packaging/releases/download/0.11.0/hello-world_0.11.0_darwin_amd64.tar.gz"
      sha256 "27500ce0cab045117d69ead4c54f303ce3f959e4c4cf2142ac0ef8ad0f54f13d"

      def install
        bin.install "hello-world"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/joshbeard/testing-packaging/releases/download/0.11.0/hello-world_0.11.0_linux_arm.tar.gz"
      sha256 "572c28c157b573a8b7d971b62c805f228aa484e0218ea99cf567c519ae1aba82"

      def install
        bin.install "hello-world"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/joshbeard/testing-packaging/releases/download/0.11.0/hello-world_0.11.0_linux_amd64.tar.gz"
      sha256 "8eb93bd35499c2e246301a362abbada96f8d28b5145905203dbed59c212f346b"

      def install
        bin.install "hello-world"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joshbeard/testing-packaging/releases/download/0.11.0/hello-world_0.11.0_linux_arm64.tar.gz"
      sha256 "5f47cf167e761af528cf9aedacbb85bf18ede85f6377a2971ac9d89b4568f108"

      def install
        bin.install "hello-world"
      end
    end
  end

  test do
    system "#{bin}/hello-world --version"
  end
end
