name: Release

on:
  push:
    tags:
      - '*.*.*'
jobs:
  build_package:
    name: Build and Package
    runs-on: self-hosted
    permissions:
      packages: write
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.21'

      - name: Import GPG Key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --import
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Build and Package
        run: |
          echo "$GPG_PRIVATE_KEY" > key.gpg
          ./build.sh install_tools
          ./build.sh release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_FINGERPRINT: ${{ secrets.GPG_FINGERPRINT }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          STAGING_DIR: /mnt/repos

  create_repos:
    name: Create Package Repos
    runs-on: self-hosted
    needs: build_package
    permissions:
      packages: write
      contents: write
    steps:
      - name: Create RPM Repository
        run: ./build.sh repo rpm
        env:
          STAGING_DIR: /mnt/repos

      - name: Create DEB Repository
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --import
          ./build.sh repo deb
        env:
          STAGING_DIR: /mnt/repos
          GPG_KEY_ID: ${{ secrets.GPG_FINGERPRINT }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Create AUR (custom) Repository
        run: ./build.sh in_docker aur-custom
        env:
          STAGING_DIR: /mnt/repos

  test_repos:
    name: Test Package Repos
    runs-on: self-hosted
    needs: create_repos
    permissions:
      packages: write
      contents: write
    steps:
      - name: Test package repos
        run: bash tests/run-tests.sh

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

  index_repos:
    name: Index Package Repos
    runs-on: self-hosted
    permissions:
      packages: write
      contents: write
    needs: test_repos
    steps:
      - name: S3 Index Generator
        run: |
          docker run --rm \
            -v /mnt/repos:/mnt/repos \
            -v ${PWD}:/workspace \
            -w /workspace \
            -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            -e AWS_REGION='us-east-1' \
            ghcr.io/joshbeard/web-indexer/web-indexer:latest

      - name: Sync directory to S3
        run: |
          /usr/local/bin/aws s3 sync /mnt/repos s3://jbeard-test-pkgs --delete --region us-east-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

  docker-hub-doc:
    name: Publish DockerHub Readme
    runs-on: ubuntu-latest
    needs: test_repos
    steps:
      - uses: actions/checkout@master
      - uses: meeDamian/sync-readme@v1.0.6
        with:
          user: ${{ secrets.DOCKERHUB_USERNAME }}
          pass: ${{ secrets.DOCKERHUB_TOKEN }}
          slug: joshbeard/hello-world
          readme: ./README.md
          description: Simple hello-world to use as an example
