name: Build and Package

on:
  push:
    tags:
      - '*.*.*'
jobs:
  build_release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.21'

    - name: Import GPG Key
      run: |
        echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --import
      env:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Login to GitHub registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

    - name: Build and Package
      run: |
        ./build.sh install_tools
        ./build.sh release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GPG_FINGERPRINT: ${{ secrets.GPG_FINGERPRINT }}

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y createrepo-c dpkg-dev

    - name: Create RPM Repository
      run: ./build.sh repo rpm

    - name: Create DEB Repository
      run: ./build.sh repo deb

    - name: Create custom AUR
      run: ./build.sh repo aur-custom-docker

    - name: Upload Artifacts to S3
      uses: jakejarvis/s3-sync-action@master
      env:
        AWS_S3_BUCKET: jbeard-test-pkgs
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'
        SOURCE_DIR: 'dist/staging'

    - name: S3 Index Generator
      uses: joshbeard/s3-index-generator@main
      with:
        config: .s3-indexer.yml
        upload: "true"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'

  docker-hub-doc:
    name: Publish DockerHub Readme
    runs-on: ubuntu-latest
    needs: build_release
    steps:
      - uses: actions/checkout@master
      - uses: meeDamian/sync-readme@v1.0.6
        with:
          user: ${{ secrets.DOCKERHUB_USERNAME }}
          pass: ${{ secrets.DOCKERHUB_TOKEN }}
          slug: joshbeard/hello-world
          readme: ./README.md
          description: Simple hello-world to use as an example
